### ISSUE TITLE
Doesn't seem to work to tmobile

### ISSUE THREAD

**Issue by markfinn** [typpo/textbelt#11]
I can email my number @tmomail.net successfully, but this service fails.  I receive a success return code, but no message gets through.  Perhaps they have blocked your sending address?

I tried it several times in the last few minutes to a number ending in 7299 if there are logs you can check.

**Comment by squilter** [comment]
I am having trouble receiving from T-Mobile again

**Comment by typpo** [comment]
I think tmobile has banned the textbelt.com domain.

**Comment by jeanmichelcote** [comment]
Probably, can't seem to receive my text messages from your service...

**Comment by daluu** [comment]
That's too bad if TMobile blocked this, maybe someone can try and convince them not to. I wonder if TMobile blocks http://www.watacrackaz.com/autosms/api.php

**Comment by sudhishkr** [comment]
TextBelt is NOT working my TMobile number. I am pretty sure its blocked.

**Comment by rsshilli** [comment]
Yup.  Definitely blocked.  I send SMSes to a group of about 30 people and everybody who uses Tmobile doesn't get the messages.

**Comment by daluu** [comment]
tmobile must be getting a lot of messages from TextBelt (and attempted messages from Textbelt's try to text all providers method) for it to consider banning the domain. Unless it's just a lame security algorithm that kicked in at tmobile based on gateway activity.

Curious @typpo, is tmobile the only provider that's banning Textbelt domain?

**Comment by sudhishkr** [comment]
@daluu @rsshilli  - for sending to TMobile, I am using Twilio API for now. I am considering switching to gmail way of sending the SMS like number@tmobile.net, there are similar mail mapping for at&t and other carriers.

**Comment by typpo** [comment]
Going to close this as I had someone confirm they are receiving texts on TMobile.

**Comment by rsshilli** [comment]
Holy crap.  It works again!  Awesome.

**Comment by sudhishkr** [comment]
Wow - @typpo : can you check your logs to see what was causing this failure before?

**Comment by typpo** [comment]
It's unclear, but I think tmobile was rejecting texts with a certain format (for example, I didn't used to set a subject), or maybe they rejected texts without some other metadata that most mailers include but sendmail does not.  I also switched servers.for good measure, but tmobile was working again before then.

**Comment by daluu** [comment]
@typpo that could make sense, I've used AutoSMS's API and they add a subject line, never had trouble with them. They also use a from/return email of "do-not-reply@textr.us", you might want to do similar so that recipients of a textbelt message know messages here aren't really "reply-able". No biggie when we send to self for notifications, and we're techies but it may be different for clueless average Joes.

**Comment by refeuerlein** [comment]
Not working for me on metropcs
