### ISSUE TITLE
Free endpoint requires API key

### ISSUE THREAD

**Issue by ikarthiks** [typpo/textbelt#117]
I am trying to test textbelt with http://textbelt.com/text but getting response as the follows, 

HTTP/1.1 200 OK
Date: Wed, 25 Oct 2017 01:17:57 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 139
Connection: keep-alive
Set-Cookie: __cfduid=db2de8b1e8fbedcd3964d2bd5405335361508894277; expires=Thu, 25-Oct-18 01:17:57 GMT; path=/; domain=.textbelt.com; HttpOnly
X-Powered-By: Express
Access-Control-Allow-Origin: *
ETag: W/"8b-8ZVZfL7mgOe9Kwr/PDcQFzeymFk"
Server: cloudflare-nginx
CF-RAY: 3b3156d054626bce-SJC

{"success":false,"error":"This Textbelt endpoint now requires a 'key' param. Please go to https://textbelt.com to sign up for an API key."}

Is this a new issue?

Please suggest if there is any workaround.

**Comment by typpo** [comment]
That's correct.  The free hosted endpoint was removed due to abuse by spammers.  It's still 100% free if you host the project yourself.

**Comment by ikarthiks** [comment]
Thanks Ian for the quick response.
