### ISSUE TITLE
Big issues installing TextBelt on Ubuntu 18.04

### ISSUE THREAD

**Issue by uiser24** [typpo/textbelt#126]
On a clean Ubuntu installation, the dependencies dont seem like they are working in package.json.

After i do: `npm install package.json`
I try start the server ./scripts/dev.sh, but it complained about 'supervisor' not being found.
I installed supervisor globally with `npm install -g supervisor`
Then started again ./scripts/dev.sh and it proceeded with the next error complaining about the following:
`Error: Cannot find module 'express'`
`Error: Cannot find module 'underscore'`
i installed express and then it broke packages but still installed and said there were 22 vulnerabilities THEN again I started the server with ./scripts/dev.sh and it complained with:
```
Error: Most middleware (like cookieParser) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.get (/home/user/TextBelt/node_modules/express/lib/express.js:108:13)
```

I tried to install the new package cookie-parser but it keeps giving the same error!!
What gives??  Am i the only one having this issue here? or have packages changed in nodejs since ubuntu 18.04 ?

Please help!!

**Comment by typpo** [comment]
I know this is a late reply, but in case anyone comes across this issue it has been resolved by updating the `express` dependency and removing the dependency on `supervisor`.
