### ISSUE TITLE
Convert to nodemailer

### ISSUE THREAD

**Issue by typpo** [typpo/textbelt#133]
Remove the mutt dependency and switch to nodemailer, which is flexible and can be configured with multiple different transports: https://nodemailer.com/about/

**Comment by Nepaltechguy2** [comment]
I was actually going to clone and change it to nodemailer for myself! I can do this if no one else is working on it.

**Comment by typpo** [comment]
@Nepaltechguy2 If you're up for it, it would be much appreciated :)
