### ISSUE TITLE
{"success":false,"message":"No carrier specified "}

### ISSUE THREAD

**Issue by kamalezzaki** [typpo/textbelt#136]
hello thank you first for this amazing project , i m tryning to send a text sms using my own server , and i get this error i m new in this project and i think that's i miss someting may be

**Comment by RyPoints** [comment]
When first configuring this I saw the same thing.  The answer is to include a carrier parameter:

curl -X POST http://127.0.0.1:9090/text -d number=4155556677 -d "message=First message." -d "carrier=verizon"

After I included that I saw an SMS connection error and configuring config.js answered that.  Then, it connected.

**Comment by typpo** [comment]
The `carrier` parameter requirement has been removed in dcfc870, although it may help improve reliability of message delivery over time.
