### ISSUE TITLE
Error: Communication with SMS gateway failed 

### ISSUE THREAD

**Issue by Helen300** [typpo/textbelt#143]
We've been trying to run the node server/app.js but we keep obtaining this error 
{"success":false,"message":"Communication with SMS gateway failed."}
and not too sure what might be causing this error

we are beginners and honestly not too sure about the various components in the code

**Comment by typpo** [comment]
I know this is a late reply but it probably means you need to edit `lib/config.js` with your mail transport settings.

Thanks for bringing this issue to my attention.  Commit a10f529 makes the error message more explicit and includes the underlying error for ease of debugging.
