### ISSUE TITLE
Trouble using with SSL 

### ISSUE THREAD

**Issue by mscroggs2017** [typpo/textbelt#151]
When I run the following code I get a mixed content error because the site this code is running from is HTTPS and it is sending to HTTP.

$.ajax({
type: "POST",
url: "http://mysite.com:9090/text",
data: { number: n, message:  message },

When I replace the http with https to combat the mixed content error, I get net::ERR_SSL_PROTOCOL_ERROR. When searching the code I can't find anything that could be the issue.

Really scratching my head on this one. Any help is appreciated.

**Comment by typpo** [comment]
Hi @mscroggs2017,

The Textbelt server is just a node server and doesn't have SSL built in.  To protect your connections, I suggest terminating SSL in front of it using nginx or another web server as a reverse proxy.

[This tutorial](https://www.linode.com/docs/web-servers/nginx/use-nginx-reverse-proxy/) may help you get started.

**Comment by mscroggs2017** [comment]
Thank you for the quick response. I will give this a try.
