### ISSUE TITLE
Status of the Project

### ISSUE THREAD

**Issue by cemalgnlts** [typpo/textbelt#163]
Hi,

Is this project still working? I have completed the installation but most addresses no longer work. Working addresses do not deliver the message.

**Comment by rpsjr** [comment]
Sees the same for me.

**Comment by typpo** [comment]
The project still works, in theory, but it will vary based on carrier.  The delivery rate of SMS-via-email (which is how this project delivers SMS for free) has dropped significantly over the years due to spam and abuse.  Many carriers block these messages now.
