### ISSUE TITLE
Is Iliad supported?

### ISSUE THREAD

**Issue by Bellisario** [typpo/textbelt#165]
I don't know if Iliad is supported...
Before I use this library, I need to know if it works.
I don't have any Iliad sim, so, I can't test by myself.
Someone know if it works?

**Comment by daluu** [comment]
Find out if Illiad has an SMS to email gateway server, that can confirm if this would work then or not as if it didn't already have it mapped, you or someone can add the gateway server to the list that textbelt uses.

**Comment by typpo** [comment]
@daluu is right, it doesn't look like we have an entry for iliad right now.
