### ISSUE TITLE
Is there a possibility to add encryption?

### ISSUE THREAD

**Issue by Eriksh** [typpo/textbelt#22]
I was looking at your code for a project I'm working on.  Unfortunately, the only thing preventing me from using it for dual-factor-authentication is the fact the system isn't encrypted.

I was wondering if there is a plan to include it?  
If not, is their a way I could fork the code and include an encryption system
that works with your server?

**Comment by mattdipasquale** [comment]
Hmm... I get "521: Web server is down" when I try:

    curl https://textbelt.com/text -d number=3525700299 -d "message=Hello, World!"

But, it works without the 's'.

**Comment by tankerkiller125** [comment]
Can confirm

**Comment by daluu** [comment]
@tankerkiller125 can confirm = confirm works or confirm fails?

I just tested using a REST client on Chrome and that works fine over HTTPS. Will try curl later.

**Comment by tankerkiller125** [comment]
I can confirm that we it works
