### ISSUE TITLE
Wiki entry as to how to run it

### ISSUE THREAD

**Issue by tankerkiller125** [typpo/textbelt#28]
It would be nice if thier was some documentation about how to run this so that we could do it ourselves on our own servers.

**Comment by daluu** [comment]
The readme kind of glosses over how to run the server. I guess it's not detailed enough though.

https://github.com/typpo/textbelt/blob/master/README.md

On a related note, the wiki section of this project (and most Github projects that have a wiki link) are (or appear to be) publicly editable. Therefore, any altruistic and experienced users of this project's server for self hosting could/should help post additional info on the wiki. Need not wait for project's author to do so.

In general, all that needs additional info or clarification on is setting up sendmail (and perhaps for Windows server instead, what might need to be done), setting up nginx or a reverse proxy for the IP based limiting, (link to) how to install node.js and npm (on various OS platforms)
