### ISSUE TITLE
denial of service 

### ISSUE THREAD

**Issue by masell** [typpo/textbelt#30]
You clame a limit based on ipaddress, however you read that "address" from httpheaders, X-real-ip, which I assume can be anything I as sender can set.
So, the limit will not work.

**Comment by daluu** [comment]
Just my thoughts, but #41 and #42 could be alternative ways to address rate limiting and abuse prevention over IP based approach. However, I speak to this from the perspective of the self hosting option. For the public hosted service, it's fine to me the way it is now.

**Comment by typpo** [comment]
IP rate limiting has been removed.
