### ISSUE TITLE
Textbelt is offline

### ISSUE THREAD

**Issue by dylangrasha** [typpo/textbelt#36]
Bad gateway to textbelt.com server

**Comment by typpo** [comment]
Thanks, it's online again.

**Comment by ahornerr** [comment]
I'm getting a 502 Gateway error since this morning (about 8am EST). @typpo

**Comment by typpo** [comment]
We're back online.

**Comment by ahornerr** [comment]
Thanks!

**Comment by ahornerr** [comment]
Hello @typpo, the Textbelt.com server appears to be down as of 8am EST 3/6/15.

**Comment by rakkihebbal** [comment]
Hi Textbelt.com/text appears to be down as of 9/28/2016

**Comment by typpo** [comment]
@rakkihebbal It's online for me and monitoring hasn't picked up downtime.  Are you receiving an error or is your connection timing out?

**Comment by rakkihebbal** [comment]
Thanks for your prompt response. I keep getting a 404 error.

**Comment by typpo** [comment]
Can you show me the command or code you're running?

**Comment by rakkihebbal** [comment]
I'm storing number and message in Concatstring, which looks like number=424*******&message=Hello  (I just masked the number here). It was working a few days ago. But today it just errors out. 

GetWindowText(hTextbox1, getTextboxText1, 50);
sprintf_s(Concatstring, _T("%s%s%s%s"),number, listviewText, smsmessage, getTextboxText1);

if (curl)
	{
		curl_easy_setopt(curl, CURLOPT_URL, "http://textbelt.com/text");
		curl_easy_setopt(curl, CURLOPT_POSTFIELDS, Concatstring);
		/* Perform the request, res will get the return code */
		res = curl_easy_perform(curl);
		/* Check for errors */
		if (res != CURLE_OK)
				fprintf(stderr, "curl_easy_perform() failed: %s\n",
				curl_easy_strerror(res));
				MessageBox(NULL, "Unable to send message.", "Error", MB_OK);
				/* always cleanup */
				curl_easy_cleanup(curl);
	}
	curl_global_cleanup();

**Comment by typpo** [comment]
I don't see a problem with the code, but you'll get a 404 if you `GET http://textbelt.com/text` instead of `POST`, so my guess is that's somehow happening.

Maybe try explicitly setting post with `CURLOPT_POST, 1`?

**Comment by rakkihebbal** [comment]
Thanks. Tested this from command line. I get "success" : true. But I am not receiving message to mobile number.

Here is my command line code:
curl -X POST http://textbelt.com/text -d number=424******* -d "message=I sent this message for free with textbelt.com"

output:
{
  "success": true
}

I'm  have AT&T as my service provider, and I was getting "message" a few days ago. For some reason not anymore.

**Comment by daluu** [comment]
That may mean AT&T isn't delivering the message after Textbelt hands it off to AT&T. Blacklisted maybe? Or AT&T outage. You can always cross check by manually sending message to AT&T's email gateway. Or use alternate SMS service to cross check AT&T service status (http://www.watacrackaz.com/autosms/api.php)
