### ISSUE TITLE
Clarification of success in readme, documentation, or actual API response 

### ISSUE THREAD

**Issue by daluu** [typpo/textbelt#44]
Currently, I believe you only get the failure message case for things like wrong phone number format and exceeding limits. Maybe bad message format too?

But in the case whether the API was able to successfully deliver the SMS or not is another story. For cases where there is no known email to SMS gateway for the target phone number's carrier, attempting to send to that number, we still get a success message, but of course the message never gets delivered because phonenumber@anycarriergateway.com never matches up and gets dropped at all the gateways.

It might be useful to clarify to users what "success" really means (as in attempted delivery has succeeded, but receipt at destination not guaranteed). If this was part of API, perhaps the success case could also include a message component that elaborates on the success for any API user who cares to read that message beyond the success = true.

Granted, I suppose users should read the limitations section to get better understanding, but from a pure API perspective, it would be nice if the API itself offered some clarification.

On a related comparison, this API would be less confusing in terms of success because, you have to select the target carrier specifically:

http://watacrackaz.com/autosms/api.php

So if message delivery does fail, it's more obvious that it may be problem with carrier gateway. Since usually it will work, except in case of user error selecting wrong carrier or typing wrong number.

Although as a consumer of this API, being a developer for some other app that uses this API, one could put in the elaboration to the end user. But assume we had a lazy developer that just passes on the API response status and message. To the end user of the final application/product, w/o reading this API's limitations (assume lazy dev didn't link the info easily), then it could be confusing to see "success" but no message delivered because there was no supported gateway in reality.

Just my two cents.

**Comment by typpo** [comment]
This is an excellent point.  Thank you for the feedback!

**Comment by daluu** [comment]
FYI, is it just me or is the update only to the readme? Did you push the changes to the site www.textbelt.com as well?
