### ISSUE TITLE
Messages sent from txt2@textbelt.com? And what are other sender addresses used?

### ISSUE THREAD

**Issue by daluu** [typpo/textbelt#46]
Not really an issue, but wanted to clarify against the site www.textbelt.com and the readme. Both state:

> Some carriers may deliver text messages from "txt@textbelt.com"

Question 1:

I use Virgin Mobile and am seeing txt2@textbelt.com. Did the email change? Or it depends on carrier? If the latter, see next question.

Question 2:

That statement says "some carriers", so what do the rest of the other carriers use for sender (address)?

**Comment by daluu** [comment]
I just noticed there is a txt4@textbelt.com today. Haven't looked at source code yet, maybe that might explain things, just wonder what the logic is for the user ID txt/txt# for from address.

**Comment by typpo** [comment]
Versions have been bumped for various reasons.  They'll generally take the form of txt*@textbelt.com.  In the past, some providers have banned the Textbelt email address (txt@textbelt.com).  In the self-hosted version, users should use their own emails by specifying `fromAddress` in `lib/text.js`.
