### ISSUE TITLE
showing invalid phone number when I call the API through objective C

### ISSUE THREAD

**Issue by ppatel03** [typpo/textbelt#58]
NSString* query = @"{\"number\":3154478103,\"message\":\"Test\"}";

NSLog(@"SMS send request Query  : %@",query);
    NSString *post = [NSString stringWithFormat:@"%@",query];
    NSData *postData = [post  dataUsingEncoding:NSUTF8StringEncoding ];  
    NSMutableURLRequest *request = [[NSMutableURLRequest alloc] init];    
    NSString *url = @"http://textbelt.com/text/";   
    
    [request setURL:[NSURL URLWithString:url]];
    [request setHTTPMethod:METHOD_POST];
    [request setHTTPBody:postData];
    
    NSLog(@"Sending the SMS to the user ");
   
    //creating the session to get the json response
    NSURLSession *session = [NSURLSession sessionWithConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration]];
    [[session dataTaskWithRequest:request  completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
        
        NSString* jsonResponse = [[NSString alloc] initWithData:data encoding:NSASCIIStringEncoding];
        NSLog(@"This is Asynchronous Response : %@",jsonResponse);
        
    }] resume];

**Comment by typpo** [comment]
You need to POST this as normal HTTP parameters, not a JSON object.  The POST body should probably look like number=XXXX&message=Test.

**Comment by typpo** [comment]
Possibly related as well is issue #45

**Comment by ppatel03** [comment]
Thank you so much !!! It worked !!!!
