### ISSUE TITLE
Bad Gateway 502 Error on TextBelt

### ISSUE THREAD

**Issue by ppatel03** [typpo/textbelt#60]
First of all, Thank you so much for providing free SMS API. I am developing a small iOS project for my curriculum. I am going to present on coming Friday 11/12. 

But suddenly there 502 error on the portal. 

Can anybody please let me know whether its a temporary issue since I needed this API to work smoothly for my demo at 11/12 2.30 pm.

Thanks !!

**Comment by typpo** [comment]
Thanks Prashant. I got an alert for this outage but I'll be out for the
next 4 hrs. I'll bring it up when I get home. Apologies for the scare.

If you need a reliability guarantee, you may want to consider self-hosting
textbelt by running the app on your own server.

**Comment by typpo** [comment]
It's back up now.

**Comment by ppatel03** [comment]
Hi,
Thank you so much !!! Much appreciated :)
