### ISSUE TITLE
Keep getting Invalid phone number error

### ISSUE THREAD

**Issue by DrSayre** [typpo/textbelt#61]
I am making my request through the Advanced REST Client which is a Google Chrome app.  I keep getting this as a response:
```
{
  "success": false,
  "message": "Invalid phone number."
}
```
I have seen this https://github.com/typpo/textbelt/issues/45 and I am setting the content-type to be application/x-www-form-urlencoded.  I have tried sending a text to both AT&T and Sprint phone.

**Comment by typpo** [comment]
Most likely it's not reading any phone number.  Make sure you are (1) sending a POST request, and (2) POSTing query params and not JSON.

**Comment by DrSayre** [comment]
That's what it was, thanks!
