### ISSUE TITLE
Duplicate Messages on Sprint phones

### ISSUE THREAD

**Issue by ChandlerSwift** [typpo/textbelt#70]
messages sent to `[number]@message.ting.com` (Ting uses the Sprint network) also get sent to Sprint phones, and so duplicate messages are received. I'd send a pull request to remove Ting, but I'm not sure if the reverse also works, so that might remove support people on that provider.

**Comment by typpo** [comment]
Hmm, it sounds like it'd be safe to remove Ting, if all Ting phones run on Sprint.

**Comment by ChandlerSwift** [comment]
I don't have a ting phone, so I can't verify that for sure. According to Wikipedia, Ting also uses T-mobile's network, so would they get duplicates too?  Either way, I'll put up a pull request to remove Ting if you'd like.

**Comment by typpo** [comment]
Thanks for reporting this and providing the pull request.  Should be fixed by #71.  It won't be live until I update the production server, which will happen soon(ish) :)
