### ISSUE TITLE
/canada not working ?

### ISSUE THREAD

**Issue by stefets** [typpo/textbelt#73]
I address my question to canadian users, 

The /canada don't work for me at this moment. I'm on T31u$

Anyone works fine with T31u$ provider ?

Thanks

**Comment by softcoder** [comment]
I'm on telus, does not seem to work

**Comment by softcoder** [comment]
Not sure how textbelt works but telus does say to send to:

Email to text
Send a text message by email using theirphonenumber@msg.telus.com as the email address. e.g. 555-123-4567@msg.telus.com

http://www.telus.com/en/bc/mobility/send-message/

**Comment by stefets** [comment]
Hi softcoder, that's a very good idea and It works fine from my Raspberry PI - I will go on that way.

Thanks !
