### ISSUE TITLE
EPIPE Error

### ISSUE THREAD

**Issue by warren8r** [typpo/textbelt#79]
Hello,
When sending text, I get the following error:
---------------------------------------------------------
txting phone 5556267989 : Hello World!
Hello World!

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:905:11)
    at Object.afterWrite (net.js:721:19)
---------------------------------------------------
I have no idea what might be causing this.
Anyone else face this issue?
Thanks,
Matt

**Comment by daluu** [comment]
Seems like a duplicate of issue #78? Or related to it anyhow. Solving that issue should likely solve this one I'd think.

**Comment by warren8r** [comment]
Hello daluu,
After reviewing some comments in #78, I believe this to be true.
I will close this one.

Thank you!

Matt
