### ISSUE TITLE
mutt - gmail reject my messages 

### ISSUE THREAD

**Issue by its2l8** [typpo/textbelt#81]
Hi 

everything is nice. but there is a problem with google
it reject my message because it thinks those are kind of 
spam, somewhere i read it can be solved by adding CC and BCC
to message , how can i do that ? i check the text.js and did somethings
but i fail

**Comment by huangminfei** [comment]
I have the same issue by using mutt. One of my gmail account fails to post mail, and another gmail account works with same receivers. Have you fixed this issue?

**Comment by typpo** [comment]
`mutt` is now removed in favor of `nodemailer` thanks to @Nepaltechguy2
