### ISSUE TITLE
How to send a voice Message

### ISSUE THREAD

**Issue by cullsin** [typpo/textbelt#83]
Hello, 

Great and Simple service. I want to send a voice message. Can you please suggest me whether you have any option Or do you know any service will provide that ?

Raja K

**Comment by typpo** [comment]
Hi Raja,

Unfortunately, Textbelt doesn't provide a voice message option.  If you're looking to place voice calls on a telephone network, I'd recommend Twilio.

**Comment by cullsin** [comment]
Hi,

Thanks a lot.  Is it possible to send a text message to +5 million people
using text message ?

Can you please suggest me how to do with Twillo ?

Raja K

**Comment by typpo** [comment]
No, you shouldn't use this to text 5 million people.  Textbelt.com will limit you after 75 texts per day.  If you self-hosted Textbelt, you'd probably be blocked by providers for spam.

If you'd like to learn more about Twilio, their [developer documentation](https://www.twilio.com/api) is probably a good place to start.  But sending 5M texts on Twilio will cost you about $40,000 in the US and even more abroad.
