### ISSUE TITLE
Self Hosting Limits?

### ISSUE THREAD

**Issue by rwedoff** [typpo/textbelt#87]
Is there still a texting limit  (75 per day) if you self host?

**Comment by daluu** [comment]
Well, one could always remove the limits in the code/config when self hosting.

**Comment by rwedoff** [comment]
I suppose that would work!

**Comment by typpo** [comment]
Thanks for bringing this up.  These sorts of things (text limits, "from"
address, etc) should really be set in a config file, not in the source.

**Comment by Nepaltechguy2** [comment]
Fixed by #94, and there shouldn't be limits when you self host.
