### ISSUE TITLE
Separate Config File

### ISSUE THREAD

**Issue by TimothyWillard** [typpo/textbelt#92]
I noticed there wasn't really a separate config file for config type stuff (fromAddress, debugEnabled, etc.) and I also saw the idea mentioned in #87. I played around with it and have something very basic, [here](https://github.com/TimothyWillard/textbelt/tree/master/lib). The way to use it is
```javascript
textbelt.config({
  fromAddress: 'something@example.com'
});
```
This doesn't cover any of the web stuff yet (I'm still going through that portion of code). But I was curious if this was the way to go with config, or what?

**Comment by typpo** [comment]
Thanks Timothy, I agree this is a good way to go.  I would welcome a pull request on this!

It's possible users might also like to specify their config in a `config.json` or `.env` (using the `dotenv`package), so that's another option.

**Comment by TimothyWillard** [comment]
I'll go ahead and open up a pull request on this, and start working on those other features.

**Comment by typpo** [comment]
Thanks - made very minor comments on the PR but it's basically good to merge.  I've added you as a collaborator so feel free to merge it when you are ready.

**Comment by Nepaltechguy2** [comment]
I was about to tackle this issue, but then it seems like it was already merged!
